{
    'name': 'Usulan Dana',
    'version': '1.0',
    'category': 'Usulan Dana',
    'summary': 'Usulan Dana Module',
    'description': 'Modul ini digunakan untuk Usulan Dana.',
    'author': 'William Purba',
    'depends': ['base', 'web_enterprise', 'account', 'hr', 'mail', 'contacts', 'purchase', 'custom_ecatalogue', 'custom_coa'],
    'data':[
        'security/approval_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/ud_approval_views.xml',
        'views/ud_setup_views.xml',
        'views/ud_up_country_views.xml',
        'views/ud_usulan_views.xml',
        'views/payment_monitoring_views.xml',
        'views/ud_plan_payment_views.xml',
        'views/account_move_views.xml',
        'views/setup_approval_views.xml',
        'views/payment_schedule_dashboard_views.xml',
        'views/ud_master_kota_views.xml',
        'views/ud_master_jenis_rencana_kerja_views.xml',
        'views/ud_master_tipe_visit_views.xml',
        'views/ud_master_tujuan_rencana_kerja_views.xml',
        'views/ud_master_jenis_transportasi_views.xml',
        'views/ud_tax_setup_views.xml',
        'views/ud_cek_tax_views.xml',
        # 'views/ud_report_plan_payment_views.xml',
        'views/ud_menus.xml',
        'wizard/payment_schedule_wizard_views.xml',
        'wizard/mass_payment_wizard_views.xml',
        'wizard/usulan_payment_choice_wizard_views.xml',
        'wizard/payment_calendar_wizard_views.xml',
        'wizard/rencana_kerja_wizard_views.xml',
        'wizard/uang_lainnya_wizard_views.xml',
    ],
    'assets':{
        'web.assets_backend': [
            'web/static/lib/Chart/Chart.js',
            'custom_usulandana/static/src/js/setup_item_list.js',
            'custom_usulandana/static/src/xml/setup_item_views.xml',
            'custom_usulandana/static/src/js/approval_dashboard.js',
            'custom_usulandana/static/src/xml/approval_dashboard.xml',
            'custom_usulandana/static/src/js/usulan_up_country_custom_bar.js',
            'custom_usulandana/static/src/xml/usulan_up_country_custom_bar.xml',
            'custom_usulandana/static/src/js/usulan_dana_custom_bar.js',
            'custom_usulandana/static/src/xml/usulan_dana_custom_bar.xml',
            'custom_usulandana/static/src/js/plan_payment.js',
            'custom_usulandana/static/src/xml/plan_payment_dashboard.xml',
            'custom_usulandana/static/src/js/payment_schedule_dashboard.js',
            'custom_usulandana/static/src/xml/payment_schedule_dashboard.xml',
            'custom_usulandana/static/src/scss/payment_schedule_dashboard.scss',
            # 'custom_usulandana/static/src/js/report_plan_payment_dashboard.js',
            # 'custom_usulandana/static/src/xml/report_plan_payment_dashboard.xml',
            # 'custom_usulandana/static/src/scss/report_plan_payment_dashboard.scss',
        ]
    },
    'auto_install': False,
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}